spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    driver-class-name: oracle.jdbc.OracleDriver
    username: sa
    password: sa
    initialization-mode: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle11gDialect
    hibernate:
      ddl-auto: update

  cache:
    type=ehcache


security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 300000